[project]
name = "docconv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pypandoc>=1.15",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"